version: '2.1'
services:
  postgresql:
    image: postgres:9
    environment:
      POSTGRES_DB: planets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    restart: always
    ports:
    - 5432:5432